name = "network-map"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = false
keep_vars = true

[[routes]]
pattern = "api.tbc.city/networks/*"
zone_name = "tbc.city"

[[r2_buckets]]
binding = "NETWORK_MAP_BUCKET"
bucket_name = "tbc-data"

[vars]
AIRTABLE_BASE_ID = "app1TcNtvts4fkqdm"
AIRTABLE_VIEW_NAME = "Map view"
NETWORKS_TABLE_NAME = "Networks"
