name = "organization-map"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = false

[[routes]]
pattern = "api.tbc.city/orgs/*"
zone_name = "tbc.city"

[[r2_buckets]]
binding = "ORG_MAP_BUCKET"
bucket_name = "<YOUR_ORG_R2_BUCKET_NAME>"  # TODO: replace with your actual R2 bucket name
