name = "disaster-data"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = false

[[routes]]
pattern = "api.tbc.city/disaster/*"
zone_name = "tbc.city"

[[r2_buckets]]
binding = "ORG_PINS_BUCKET"
bucket_name = "<tbc-data>"
