name: Mirror to Maps Repository
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with token
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: YOUR_NEW_WORKING_TOKEN
          
      - name: Configure git
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"
          
      - name: Add remote and push
        run: |
          git remote add mirror https://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@github.com/pastorplt/tbc_public_maps.git
          git push mirror main --force
