name: Mirror to tbc_public_maps

on:
#  push:
#    branches:
#      - '**'
#    tags:
#      - '**'
#  delete:
  workflow_dispatch:
#  schedule:
#    - cron: '17 7 * * *'

permissions:
  contents: read

concurrency:
  group: mirror
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for pushing to target
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

      - name: Trust github.com host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror-clone the source (bare)
        run: |
          set -euxo pipefail
          git clone --mirror "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" mirror.git

      - name: Prepare Git LFS (optional)
        run: |
          set -euxo pipefail
          if command -v git-lfs >/dev/null 2>&1; then
            git -C mirror.git lfs install --local
            git -C mirror.git lfs fetch --all || true
          else
            echo "git-lfs not installed; skipping LFS steps"
          fi

      - name: Push everything to target (branches, tags, deletions)
        run: |
          set -euxo pipefail
          git -C mirror.git remote add mirror "git@github.com:pastorplt/tbc_public_maps.git"
          git -C mirror.git push --mirror mirror
          if command -v git-lfs >/dev/null 2>&1; then
            git -C mirror.git lfs push --all mirror || true
          fi
