name: Mirror to Maps Repository
on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # This is key - prevents default auth
          
      - name: Configure git with token
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"
          
      - name: Clear existing git credentials
        run: |
          git config --unset-all http.https://github.com/.extraheader || true
          
      - name: Mirror to destination repository
        run: |
          git remote add mirror https://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@github.com/pastorplt/tbc_public_maps.git
          git push mirror --all --force
          git push mirror --tags --force
