name: Mirror to Maps Repository
on:
  push:
    branches: ['**']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure git
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"
          
      - name: Mirror to destination repository
        run: |
          git remote add mirror https://${{ secrets.PAT_TOKEN }}@github.com/${{ secrets.MIRROR_REPO }}.git
          git push mirror --all --force
          git push mirror --tags --force
