name: Mirror to Maps Repository
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Don't specify token here - use default
          
      - name: Configure git and mirror
        env:
          TOKEN: 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
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"
          git remote add mirror https://${TOKEN}@github.com/pastorplt/tbc_public_maps.git
          git push mirror main --force
