name: Mirror to Maps Repository
on:
  push:
    branches: ['**']
  create:
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Mirror to destination repository
        run: |
          git remote add mirror https://${{ secrets.MIRROR_TOKEN }}@github.com/${{ secrets.MIRROR_REPO }}.git
          git push mirror --all --force
          git push mirror --tags --force
