name: Mirror to tbc_public_maps

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  delete:
  workflow_dispatch:
  schedule:
    - cron: '17 7 * * *'

permissions:
  contents: read

concurrency:
  group: mirror
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror-clone the source (bare)
        run: |
          set -euxo pipefail
          git clone --mirror "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" mirror.git

      - name: Prepare Git LFS (optional)
        run: |
          set -euxo pipefail
          if command -v git-lfs >/dev/null 2>&1; then
            git -C mirror.git lfs install --local
            git -C mirror.git lfs fetch --all || true
          else
            echo "git-lfs not installed; skipping LFS steps"
          fi

      - name: Push everything to target (branches, tags, deletions)
        env:
          MIRROR_URL: https://x-access-token:${{ secrets.MIRROR_PUSH_TOKEN }}@github.com/pastorplt/tbc_public_maps.git
        run: |
          set -euxo pipefail
          git -C mirror.git remote add mirror "$MIRROR_URL"
          git -C mirror.git push --mirror mirror
          if command -v git-lfs >/dev/null 2>&1; then
            git -C mirror.git lfs push --all mirror || true
          fi
