name: Mirror to Maps Repository
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure git and credentials
        env:
          TOKEN: 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
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "actions@github.com"
          
          # Configure git to use the token for github.com
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          
      - name: Add remote and push
        run: |
          git remote add mirror https://github.com/pastorplt/tbc_public_maps.git
          git push mirror main --force
