name: Debug Mirror Setup
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug secrets and environment
        run: |
          echo "=== Environment Info ==="
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          
          echo "=== Secret Status ==="
          if [ -n "${{ secrets.NEW_MIRROR_TOKEN }}" ]; then
            echo "✅ NEW_MIRROR_TOKEN is set (length: ${#NEW_MIRROR_TOKEN})"
            echo "Token starts with: ${NEW_MIRROR_TOKEN:0:4}..."
          else
            echo "❌ NEW_MIRROR_TOKEN is not set"
          fi
          
          if [ -n "${{ secrets.MIRROR_REPO }}" ]; then
            echo "✅ MIRROR_REPO is set: ${{ secrets.MIRROR_REPO }}"
          else
            echo "❌ MIRROR_REPO is not set"
          fi
          
      - name: Test GitHub API access
        run: |
          echo "=== Testing GitHub API ==="
          curl -H "Authorization: token ${{ secrets.NEW_MIRROR_TOKEN }}" \
               -s -o /tmp/user.json \
               -w "HTTP Status: %{http_code}\n" \
               https://api.github.com/user
          
          if [ -f /tmp/user.json ]; then
            echo "API Response:"
            cat /tmp/user.json | head -5
          fi
          
      - name: Test destination repository access
        run: |
          echo "=== Testing destination repository access ==="
          curl -H "Authorization: token ${{ secrets.NEW_MIRROR_TOKEN }}" \
               -s -o /tmp/repo.json \
               -w "HTTP Status: %{http_code}\n" \
               "https://api.github.com/repos/${{ secrets.MIRROR_REPO }}"
               
          if [ -f /tmp/repo.json ]; then
            echo "Repository API Response:"
            cat /tmp/repo.json | head -10
          fi
          
      - name: Test git operations
        run: |
          echo "=== Testing Git Operations ==="
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          echo "Attempting to add remote..."
          git remote add test-mirror https://${{ secrets.NEW_MIRROR_TOKEN }}@github.com/${{ secrets.MIRROR_REPO }}.git
          
          echo "Attempting to fetch from remote..."
          git ls-remote test-mirror || echo "ls-remote failed with exit code $?"
          
      - name: Show git remotes
        run: |
          echo "=== Current Git Remotes ==="
          git remote -v
